import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.MapProperty
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

/** Generates `AppConfig.kt` (build-time config from local.properties / env vars). Configuration-cache safe. */
@CacheableTask
abstract class GenerateAppConfigTask : DefaultTask() {
    @get:Input
    abstract val values: MapProperty<String, String>

    @get:Input
    abstract val packageName: org.gradle.api.provider.Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val pkg = packageName.get()
        val file = outputDir.get().file("${pkg.replace('.', '/')}/AppConfig.kt").asFile
        file.parentFile.mkdirs()
        val fields = values.get().entries.sortedBy { it.key }.joinToString("\n") { (k, v) ->
            "    const val $k: String = \"${v.replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$")}\""
        }
        file.writeText(
            """
            |// GENERATED by generateAppConfig from local.properties / environment. Do not edit.
            |package $pkg
            |
            |object AppConfig {
            |$fields
            |
            |    val isConfigured: Boolean get() = SUPABASE_URL.startsWith("https://") && !SUPABASE_URL.contains("placeholder")
            |}
            |
            """.trimMargin(),
        )
    }
}
